spring:
  application:
    name: HelloMessageQueue
  rabbitmq:
    host: localhost
    port: 5672 #15672 -> amdin ui ?? ??
    username: guestuser
    password: guestuser
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 1000
        default-requeue-rejected: false

server:
  port: 8080
