INSERT INTO TB_USER (USER_ID, USER_NAME, USER_PASSWORD, USER_EMAIL, IS_USE, CREATED_ON, CREATED_USER,
                     CREATED_USER_ID, LAST_EDITED_ON, LAST_EDITED_USER, LAST_EDITED_USER_ID)
VALUES ('b7e5a5b3-5f4a-4c8b-9e18-5b1c8e2f3d4a', 'admin', '$2a$10$z0wqR6EBo3p1ixDqGVxY0.YdPYYbv9uTe08YP2Qw95X647yr8J1fm',
'admin@admin.com', true, now(), 'SYSTEM_USER', 'SYSTEM_USER', now(), 'SYSTEM_USER', 'SYSTEM_USER');


