### Logger setting ###
logging:
  config: file:${setting.logging.file-path}

server:
  port: ${setting.server.port}
  servlet:
    context-path: ${setting.server.context-path}

spring:
  application:
    name: spring_alert
  profiles:
    active: default, setting

  devtools:
    restart:
      enabled: false

  ## database setting ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:h2:mem:${setting.database.rdbms.schema};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: ${setting.database.rdbms.username}
    password: ${setting.database.rdbms.password}
    current-schema: ${setting.database.rdbms.current-schema}

  h2:
    console:
      enabled: true
      path: /h2-console


  ## jpa setting ##
  jpa:
    hibernate:
      ddl-auto: ${setting.database.rdbms.ddl-auto:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: ${setting.database.rdbms.current-schema}  # 스키마 설정
    open-in-view: false
    defer-datasource-initialization: true # table 생성 후 data.sql 실행
  sql:
    init:
      mode: ${setting.database.sql.init.mode:never}
      encoding: UTF-8
#      data-locations: classpath:data.sql